### ISSUE TITLE
Train on cpu or 1 gpu

### ISSUE THREAD

**Issue by HamDan1999** [ouc-ocean-group/RRNet#12]
Hi,

I want to train my model on cpu or 1 gpu.
Can you please guide me through the steps of not using distributed wrapper for training.

**Comment by GeoffreyChen777** [comment]
https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/scripts/RRNet/train.py#L7

->

```
dis_operator = RRNetOperator(Config) 
```


https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/configs/rrnet_config.py#L88

->

```
Config.Distributed.gpu_id = 0
```


It's not recommended to train rrnet on cpu. It's very slow.

And I guess 1 GPU cannot reproduce the performance we reported in the paper because of small batch size.

**Comment by HamDan1999** [comment]
Thanks for your quick response, much appreciated.

In line 8 in scripts/RRNet/train.py , there is no Train method for dis_operator = RRNetOperator(Config) 

[RRNet/scripts/RRNet/train.py](https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/scripts/RRNet/train.py#L8)

How could I train it?

**Comment by GeoffreyChen777** [comment]
Just call `training_process`

https://github.com/ouc-ocean-group/RRNet/blob/d0f37a6a7697ac7ea775e513fe8a07c8d1ab1b5d/operators/rrnet_operator.py#L104

**Comment by HamDan1999** [comment]
Thanks again,

And sorry for this, can you please send me or attach the nms and soft_nms. (The one that you get from running cd ext/nms && make && cd ..)


I keep getting errors when trying to make them.

My eamil is: mohdalansari99@hotmail.com

**Comment by GeoffreyChen777** [comment]
Sorry I don't have them now. I have no access to the machine of my previous institution.

The code of nms and soft-nm were not developed by us, please search your error via google to solve it.

**Comment by HamDan1999** [comment]
Noted with thanks.

Thanks for your time.
